server:
  port: 8008
spring:
  application:
    name: demo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/login?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
#  mvc:
#    view:
#      prefix: /
#      suffix: .html


# mybatis-plus相关配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity


#日志配置



